name: "Install Dependencies"
description: "Install dependencies, fetching from cache when possible"
inputs:
  node-version:
    description: the version of Node.js to install
    default: 22

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    # Enable node compile cache (effective for Node 22+)
    # See https://nodejs.org/docs/v24.11.1/api/module.html#module-compile-cache
    - name: Enable Node Compile Cache
      shell: bash
      run: echo "NODE_COMPILE_CACHE=$HOME/.node_compile_cache" >> $GITHUB_ENV

    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
