packages:
  - packages/*
  - examples/*
  - examples/e2e/*
  - benchmarking

catalog:
  "@cloudflare/workers-types": ^4.20241230.0
  "@dotenvx/dotenvx": 1.31.0
  "@eslint/js": ^9.11.1
  "@playwright/test": 1.47.0
  "@tsconfig/strictest": ^2.0.5
  "@types/mock-fs": ^4.13.4
  "@types/node": ^22.2.0
  "@types/react-dom": ^18
  "@types/react": ^18
  esbuild: ^0.23.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-unicorn: ^55.0.0
  eslint: ^9.11.1
  glob: ^11.0.0
  globals: ^15.9.0
  mock-fs: ^5.4.1
  next: 14.2.11
  package-manager-detector: ^0.2.0
  react-dom: ^18
  react: ^18
  rimraf: ^6.0.1
  ts-morph: ^23.0.0
  tsup: ^8.2.4
  tsx: ^4.19.2
  typescript-eslint: ^8.7.0
  typescript: ^5.7.3
  vitest: ^2.1.1
  wrangler: ^3.103.0

# e2e tests
catalogs:
  e2e:
    "@types/node": 20.17.6
    "@types/react-dom": 19.0.0
    "@types/react": 19.0.0
    autoprefixer: 10.4.15
    next: 15.1.0
    postcss: 8.4.27
    react-dom: 19.0.0
    react: 19.0.0
    tailwindcss: 3.3.3
