packages:
  - "packages/*"
  - "examples/*"
  - "benchmarking"

catalog:
  "@cloudflare/workers-types": ^4.20240925.0
  "@dotenvx/dotenvx": 1.31.0
  "@eslint/js": ^9.11.1
  "@playwright/test": 1.47.0
  "@tsconfig/strictest": "^2.0.5"
  "@types/mock-fs": ^4.13.4
  "@types/node": ^22.2.0
  "@types/react-dom": ^18
  "@types/react": ^18
  "esbuild": ^0.23.0
  "eslint-plugin-import": "^2.31.0"
  "eslint-plugin-simple-import-sort": "^12.1.1"
  "eslint-plugin-unicorn": ^55.0.0
  "eslint": ^9.11.1
  "glob": ^11.0.0
  "globals": ^15.9.0
  "mock-fs": ^5.4.1
  "next": 14.2.11
  "package-manager-detector": ^0.2.0
  "react-dom": ^18
  "react": ^18
  "rimraf": "^6.0.1"
  "ts-morph": ^23.0.0
  "tsup": ^8.2.4
  "tsx": ^4.19.2
  "typescript-eslint": ^8.7.0
  "typescript": ^5.5.4
  "vitest": ^2.1.1
  "wrangler": ^3.99.0
