#:schema node_modules/wrangler/config-schema.json
name = "vercel-blog-starter-on-workers"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
